### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by eamonnfaherty-productmadness** [silentsound/baiocas#1]
Could you please create a readme with basic usage please?

I would love to use this library but I am not sure how :confused:

**Comment by eamonnfaherty-productmadness** [comment]
So far I have the following but I am not receiving messages:

import logging
from baiocas.client import Client
from baiocas.transports.long_polling import LongPollingHttpTransport
from tornado.ioloop import IOLoop

server = "http://myserver.com"
channel = "/mychannel" 

FORMAT = '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
logging.basicConfig(
    level=logging.INFO,
    format=FORMAT,
)

def onMessage(data):
    print data

io_loop = IOLoop.instance()
client = Client(server, io_loop=io_loop)
transport = LongPollingHttpTransport()
client.register_transport(transport)
client.initialize()

channel = client.get_channel(channel)
channel.subscribe(onMessage)

io_loop.start()

**Comment by eamonnfaherty-productmadness** [comment]
I managed to get it working.  I had an external issue to resolve first but the working code I am using is:

    client = Client(server_to_join)
    transport = LongPollingHttpTransport()
    client.register_transport(transport)
    client.initialize()
    channel = self.client.get_channel(channel_to_join)
    channel.subscribe(self.onMessage)
    IOLoop.current().start()

    def onMessage(self, channel, message):
        pass

**Comment by silentsound** [comment]
Apologies for the delay @eamonnfaherty-productmadness! I am not actively maintaining this library at the moment. That said, it looks like you figured it out. Here's the way I'm using it:

```python
import signal

from baiocas.channel_id import ChannelId
from baiocas.client import get_client
from tornado.ioloop import IOLoop

# Get an IOLoop instance
io_loop = IOLoop.instance()

# Register signal handlers so we shutdown cleanly
for signum in (signal.SIGINT, signal.SIGTERM, signal.SIGQUIT):
	signal.signal(signum, shutdown)

# Set up the streaming client
streaming_client = get_client(server_url, io_loop=io_loop)
for name in streaming_client.get_known_transports():
	transport = streaming_client.get_transport(name)
	if hasattr(transport, 'add_header'):
		transport.add_header('Authorization', 'OAuth %s' % session_id)

# Add a listener for all unsuccessful messages
streaming_client.get_channel(ChannelId.META_UNSUCCESSFUL).add_listener(receive_failure)

# Add a listener to log listener exceptions
streaming_client.register_listener(
	streaming_client.EVENT_LISTENER_EXCEPTION,
	handle_exception
)

# Set up listeners on handshake and start the handshake. We need a
# listener here so that we subscribe back to the topics whenever the
# server asks us to re-handshake (which loses all subscribed topics).
streaming_client.get_channel(ChannelId.META_HANDSHAKE).add_listener(subscribe)
streaming_client.handshake()

# Start the IOLoop
io_loop.start()
```

And on handshake, I'm doing:

```python
def subscribe(channel, message):
	if message.successful:
		channel = streaming_client.get_channel(topic)
		channel.subscribe(receive_message)
```

Hopefully this helps a bit should you encounter anymore issues.

**Comment by eamonnfaherty-productmadness** [comment]
Thanks in double then!  I will adopt your code and hope this may help anyone else in need.
